name: Publish

on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Import and Publish
        run: |
          shortcuts import payload.shortcut
          osascript -e '
          tell application "Shortcuts"
              set theShortcut to shortcut named "تحديث أمان iOS"
              set theURL to publish theShortcut
              return theURL
          end tell
          ' > url.txt
          echo "الرابط: $(cat url.txt)"
      - uses: actions/upload-artifact@v3
        with:
          name: shortcut-url
          path: url.txt
